### ISSUE TITLE
How to normalize the challenge score in to [0, 60]

### ISSUE THREAD

**Issue by MTonyM** [CS150-DataBase-ShanghaiTech/CourseProject#1]
As you said 
```Python
score = -40.0*log(A)/log(2) - 60.0*log(B)/log(2)
#Described using python language
```
the maximum score will be about `332.19` when `A = 0.1` and `B =0.1`,(roughly estimate.) So how to normalize this score to [0, 60] ?

**Comment by tonysy** [comment]
Good Questions. 

We follow this protocol to get the highest score **H** and the lowest score **L** in our class. 
Also, we will provide a baseline with a simplified model(we will give the details of the baseline model but without code).

The final grade of the baseline is a threshold at 60*0.6=36, the score of baseline model is **M**.
If you are hihger the the score of baseline. We will use the M and H to generate your grade. Your final grade is higher than 36. 

If you follow the pipeline and details of our baseline model, you will get 36 at least definitely.
Details of baseline will be uploaded in two weeks, while we hope you guys try your best first.

Keep working and you will get your return.
